### ISSUE TITLE
Got 'no matching function for call' error

### ISSUE THREAD

**Issue by wlad031** [ngrodzitski/json_dto#1]
When I try to build the project with json_dto, I get the following error:
```
json_dto/pub.hpp:210:33: error: no matching function for call to 'rapidjson::GenericValue<rapidjson::UTF8<> >::SetString(const string&, rapidjson::MemoryPoolAllocator<>&)'
  object.SetString( s, allocator );
```

**Comment by ngrodzitski** [comment]
Hi, Vlad!
Can you provide some details to help me to reproduce the error?

Compiler, version of RapidJSON and defined macros that customize its build?

**Comment by wlad031** [comment]
I've sent you [pull request](https://github.com/ngrodzitski/json_dto-0.1/pull/3) that fixes this issue

I use g++ 6
```
$ g++-6 --version
g++-6 (Homebrew GCC 6.3.0_1) 6.3.0
```
I use RapidJSON from it's official repo (TAG v.1.1.0)

P.S. I should say that I use CMake for building my project. 
```
EXTERNALPROJECT_ADD(
        RapidJSON
        GIT_REPOSITORY https://github.com/miloyip/rapidjson
        GIT_TAG v1.1.0
        SOURCE_DIR ${RAPID_JSON_DIRECTORY}
        BINARY_DIR ${RAPID_JSON_BUILD_DIRECTORY}
        UPDATE_COMMAND ""
        PATCH_COMMAND ${CMAKE_COMMAND} -E copy ${RAPID_JSON_DIRECTORY}/CMakeLists.txt ${CMAKE_BINARY_DIR}/RapidJSON/CMakeLists.txt
        CMAKE_GENERATOR ${gen}
        CMAKE_ARGS
        ${ep_common_args}
        -DCMAKE_BUILD_TYPE:STRING=Release
        -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_BINARY_DIR}/INSTALL
)
SET(RAPID_JSON_INCLUDE ${CMAKE_BINARY_DIR}/INSTALL/include)

# json_dto
SET(JSON_DTO_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/json_dto)

EXTERNALPROJECT_ADD(
        json_dto
        GIT_REPOSITORY https://github.com/wlad031/json_dto-0.1
        SOURCE_DIR ${JSON_DTO_DIRECTORY}
        BINARY_DIR ${JSON_DTO_BUILD_DIRECTORY}
        PATCH_COMMAND ${CMAKE_COMMAND} -E copy_directory ${JSON_DTO_DIRECTORY}/dev/json_dto ${RAPID_JSON_INCLUDE}/json_dto
        BUILD_IN_SOURCE 1
        CONFIGURE_COMMAND ""
        BUILD_COMMAND ""
        INSTALL_COMMAND ""
)
SET(JSON_DTO_INCLUDE ${JSON_DTO_BUILD_DIRECTORY}/INSTALL/include)
```

**Comment by ngrodzitski** [comment]
I've seen pull request, and it just turn std::string argument to c-string. 
And I've checked RapidJSON API for [that function](http://rapidjson.org/classrapidjson_1_1_generic_value.html#a3e930bffb40a78e570e3deef461f0532) and I think a better solution is to define `RAPIDJSON_HAS_STDSTRING` for RapidJSON project upsred for all projects that depend on it (directly or not). 
I guess you are using std::string in ordinary way in your project, so to use `RAPIDJSON_HAS_STDSTRING` is not an issue. The sad fact is that header-only libs are customizable via macro definitions, so a user of the library should consider them.
